@startuml

rectangle "subject.monitor dependency graph" {
    (ec2.status) <-- (vkvma.connect)
    (vkvma.connect) <-- (vkvma.health)
    (vkvma.health) <-- (app.health)
    (vkvma.connect) <-- (app.watch)
}
note "a **subject.monitor** can't succeed if another it points to is //failing//" as N1

@enduml
