//
//This sample, non-production-ready code contains a Virtual Kubelet EC2-based provider and example VM Agent implementation.
//© 2021 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
//
//This AWS Content is provided subject to the terms of the AWS Customer Agreement
//available at http://aws.amazon.com/agreement or other written agreement between
//Customer and either Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

// This file describes the application lifecycle API exposed by the VKVMAgent.  The agent manages one or more
// "applications".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: vkvmagent/v0/application_lifecycle.proto

package vkvmagent_v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "k8s.io/api/core/v1"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LaunchApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pod *v1.Pod `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
}

func (x *LaunchApplicationRequest) Reset() {
	*x = LaunchApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LaunchApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchApplicationRequest) ProtoMessage() {}

func (x *LaunchApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchApplicationRequest.ProtoReflect.Descriptor instead.
func (*LaunchApplicationRequest) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_application_lifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *LaunchApplicationRequest) GetPod() *v1.Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

type LaunchApplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LaunchApplicationResponse) Reset() {
	*x = LaunchApplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LaunchApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchApplicationResponse) ProtoMessage() {}

func (x *LaunchApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchApplicationResponse.ProtoReflect.Descriptor instead.
func (*LaunchApplicationResponse) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_application_lifecycle_proto_rawDescGZIP(), []int{1}
}

type TerminateApplicationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TerminateApplicationRequest) Reset() {
	*x = TerminateApplicationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateApplicationRequest) ProtoMessage() {}

func (x *TerminateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateApplicationRequest.ProtoReflect.Descriptor instead.
func (*TerminateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_application_lifecycle_proto_rawDescGZIP(), []int{2}
}

type TerminateApplicationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TerminateApplicationResponse) Reset() {
	*x = TerminateApplicationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateApplicationResponse) ProtoMessage() {}

func (x *TerminateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateApplicationResponse.ProtoReflect.Descriptor instead.
func (*TerminateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_application_lifecycle_proto_rawDescGZIP(), []int{3}
}

type ApplicationHealthRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ApplicationHealthRequest) Reset() {
	*x = ApplicationHealthRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationHealthRequest) ProtoMessage() {}

func (x *ApplicationHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationHealthRequest.ProtoReflect.Descriptor instead.
func (*ApplicationHealthRequest) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_application_lifecycle_proto_rawDescGZIP(), []int{4}
}

type ApplicationHealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodStatus *v1.PodStatus `protobuf:"bytes,1,opt,name=podStatus,proto3" json:"podStatus,omitempty"`
}

func (x *ApplicationHealthResponse) Reset() {
	*x = ApplicationHealthResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApplicationHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationHealthResponse) ProtoMessage() {}

func (x *ApplicationHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_application_lifecycle_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationHealthResponse.ProtoReflect.Descriptor instead.
func (*ApplicationHealthResponse) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_application_lifecycle_proto_rawDescGZIP(), []int{5}
}

func (x *ApplicationHealthResponse) GetPodStatus() *v1.PodStatus {
	if x != nil {
		return x.PodStatus
	}
	return nil
}

var File_vkvmagent_v0_application_lifecycle_proto protoreflect.FileDescriptor

var file_vkvmagent_v0_application_lifecycle_proto_rawDesc = []byte{
	0x0a, 0x28, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x30, 0x2f, 0x61,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x66, 0x65, 0x63,
	0x79, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x76, 0x6b, 0x76, 0x6d,
	0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x1a, 0x22, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x18,
	0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x03, 0x70, 0x6f, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6b, 0x38, 0x73, 0x2e, 0x69, 0x6f, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6f, 0x64, 0x52, 0x03,
	0x70, 0x6f, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1d, 0x0a, 0x1b, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1e, 0x0a, 0x1c, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x1a, 0x0a, 0x18, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65,
	0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x58, 0x0a, 0x19, 0x41,
	0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x09, 0x70, 0x6f, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x38,
	0x73, 0x2e, 0x69, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x72, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x50, 0x6f, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x09, 0x70, 0x6f, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xc3, 0x03, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x64,
	0x0a, 0x11, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x26, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e,
	0x76, 0x30, 0x2e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x76, 0x6b,
	0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x4c, 0x61, 0x75, 0x6e, 0x63,
	0x68, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6d, 0x0a, 0x14, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74,
	0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x2e, 0x76,
	0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x54, 0x65, 0x72, 0x6d,
	0x69, 0x6e, 0x61, 0x74, 0x65, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x54, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x69, 0x0a, 0x16, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x41, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x26, 0x2e,
	0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x70, 0x70,
	0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x6b,
	0x0a, 0x16, 0x57, 0x61, 0x74, 0x63, 0x68, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x12, 0x26, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x6c, 0x74, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x27, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e,
	0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x6c, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x42, 0x35, 0x5a, 0x33, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x77, 0x73, 0x2f, 0x61, 0x77,
	0x73, 0x2d, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x2d, 0x6b, 0x75, 0x62, 0x65, 0x6c, 0x65,
	0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f,
	0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vkvmagent_v0_application_lifecycle_proto_rawDescOnce sync.Once
	file_vkvmagent_v0_application_lifecycle_proto_rawDescData = file_vkvmagent_v0_application_lifecycle_proto_rawDesc
)

func file_vkvmagent_v0_application_lifecycle_proto_rawDescGZIP() []byte {
	file_vkvmagent_v0_application_lifecycle_proto_rawDescOnce.Do(func() {
		file_vkvmagent_v0_application_lifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(file_vkvmagent_v0_application_lifecycle_proto_rawDescData)
	})
	return file_vkvmagent_v0_application_lifecycle_proto_rawDescData
}

var file_vkvmagent_v0_application_lifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vkvmagent_v0_application_lifecycle_proto_goTypes = []interface{}{
	(*LaunchApplicationRequest)(nil),     // 0: vkvmagent.v0.LaunchApplicationRequest
	(*LaunchApplicationResponse)(nil),    // 1: vkvmagent.v0.LaunchApplicationResponse
	(*TerminateApplicationRequest)(nil),  // 2: vkvmagent.v0.TerminateApplicationRequest
	(*TerminateApplicationResponse)(nil), // 3: vkvmagent.v0.TerminateApplicationResponse
	(*ApplicationHealthRequest)(nil),     // 4: vkvmagent.v0.ApplicationHealthRequest
	(*ApplicationHealthResponse)(nil),    // 5: vkvmagent.v0.ApplicationHealthResponse
	(*v1.Pod)(nil),                       // 6: k8s.io.api.core.v1.Pod
	(*v1.PodStatus)(nil),                 // 7: k8s.io.api.core.v1.PodStatus
}
var file_vkvmagent_v0_application_lifecycle_proto_depIdxs = []int32{
	6, // 0: vkvmagent.v0.LaunchApplicationRequest.pod:type_name -> k8s.io.api.core.v1.Pod
	7, // 1: vkvmagent.v0.ApplicationHealthResponse.podStatus:type_name -> k8s.io.api.core.v1.PodStatus
	0, // 2: vkvmagent.v0.ApplicationLifecycle.LaunchApplication:input_type -> vkvmagent.v0.LaunchApplicationRequest
	2, // 3: vkvmagent.v0.ApplicationLifecycle.TerminateApplication:input_type -> vkvmagent.v0.TerminateApplicationRequest
	4, // 4: vkvmagent.v0.ApplicationLifecycle.CheckApplicationHealth:input_type -> vkvmagent.v0.ApplicationHealthRequest
	4, // 5: vkvmagent.v0.ApplicationLifecycle.WatchApplicationHealth:input_type -> vkvmagent.v0.ApplicationHealthRequest
	1, // 6: vkvmagent.v0.ApplicationLifecycle.LaunchApplication:output_type -> vkvmagent.v0.LaunchApplicationResponse
	3, // 7: vkvmagent.v0.ApplicationLifecycle.TerminateApplication:output_type -> vkvmagent.v0.TerminateApplicationResponse
	5, // 8: vkvmagent.v0.ApplicationLifecycle.CheckApplicationHealth:output_type -> vkvmagent.v0.ApplicationHealthResponse
	5, // 9: vkvmagent.v0.ApplicationLifecycle.WatchApplicationHealth:output_type -> vkvmagent.v0.ApplicationHealthResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vkvmagent_v0_application_lifecycle_proto_init() }
func file_vkvmagent_v0_application_lifecycle_proto_init() {
	if File_vkvmagent_v0_application_lifecycle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vkvmagent_v0_application_lifecycle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LaunchApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_application_lifecycle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LaunchApplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_application_lifecycle_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateApplicationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_application_lifecycle_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TerminateApplicationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_application_lifecycle_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationHealthRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_application_lifecycle_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApplicationHealthResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vkvmagent_v0_application_lifecycle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vkvmagent_v0_application_lifecycle_proto_goTypes,
		DependencyIndexes: file_vkvmagent_v0_application_lifecycle_proto_depIdxs,
		MessageInfos:      file_vkvmagent_v0_application_lifecycle_proto_msgTypes,
	}.Build()
	File_vkvmagent_v0_application_lifecycle_proto = out.File
	file_vkvmagent_v0_application_lifecycle_proto_rawDesc = nil
	file_vkvmagent_v0_application_lifecycle_proto_goTypes = nil
	file_vkvmagent_v0_application_lifecycle_proto_depIdxs = nil
}
