//
//This sample, non-production-ready code contains a Virtual Kubelet EC2-based provider and example VM Agent implementation.
//© 2021 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
//
//This AWS Content is provided subject to the terms of the AWS Customer Agreement
//available at http://aws.amazon.com/agreement or other written agreement between
//Customer and either Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

// This file describes the bootstrap API exposed by the VKVMAgent.  This API is used by the VKProvider to establish
// a secure channel for future communications.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: vkvmagent/v0/bootstrap.proto

package vkvmagent_v0

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAgentIdentityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAgentIdentityRequest) Reset() {
	*x = GetAgentIdentityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentIdentityRequest) ProtoMessage() {}

func (x *GetAgentIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetAgentIdentityRequest) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_bootstrap_proto_rawDescGZIP(), []int{0}
}

type GetAgentIdentityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ec2InstanceIdentity *EC2InstanceIdentity `protobuf:"bytes,1,opt,name=ec2InstanceIdentity,proto3" json:"ec2InstanceIdentity,omitempty"`
}

func (x *GetAgentIdentityResponse) Reset() {
	*x = GetAgentIdentityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAgentIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentIdentityResponse) ProtoMessage() {}

func (x *GetAgentIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetAgentIdentityResponse) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *GetAgentIdentityResponse) GetEc2InstanceIdentity() *EC2InstanceIdentity {
	if x != nil {
		return x.Ec2InstanceIdentity
	}
	return nil
}

type EC2InstanceIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InstanceDocument   []byte `protobuf:"bytes,1,opt,name=instanceDocument,proto3" json:"instanceDocument,omitempty"`
	Pkcs7Signature     []byte `protobuf:"bytes,2,opt,name=pkcs7Signature,proto3" json:"pkcs7Signature,omitempty"`
	SigningCertificate []byte `protobuf:"bytes,3,opt,name=signingCertificate,proto3" json:"signingCertificate,omitempty"`
}

func (x *EC2InstanceIdentity) Reset() {
	*x = EC2InstanceIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EC2InstanceIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EC2InstanceIdentity) ProtoMessage() {}

func (x *EC2InstanceIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EC2InstanceIdentity.ProtoReflect.Descriptor instead.
func (*EC2InstanceIdentity) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *EC2InstanceIdentity) GetInstanceDocument() []byte {
	if x != nil {
		return x.InstanceDocument
	}
	return nil
}

func (x *EC2InstanceIdentity) GetPkcs7Signature() []byte {
	if x != nil {
		return x.Pkcs7Signature
	}
	return nil
}

func (x *EC2InstanceIdentity) GetSigningCertificate() []byte {
	if x != nil {
		return x.SigningCertificate
	}
	return nil
}

type LaunchAuthenticatedEndpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PemCertificateChain []byte `protobuf:"bytes,1,opt,name=pemCertificateChain,proto3" json:"pemCertificateChain,omitempty"`
	PemPrivateKey       []byte `protobuf:"bytes,2,opt,name=pemPrivateKey,proto3" json:"pemPrivateKey,omitempty"`
}

func (x *LaunchAuthenticatedEndpointRequest) Reset() {
	*x = LaunchAuthenticatedEndpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LaunchAuthenticatedEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchAuthenticatedEndpointRequest) ProtoMessage() {}

func (x *LaunchAuthenticatedEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchAuthenticatedEndpointRequest.ProtoReflect.Descriptor instead.
func (*LaunchAuthenticatedEndpointRequest) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (x *LaunchAuthenticatedEndpointRequest) GetPemCertificateChain() []byte {
	if x != nil {
		return x.PemCertificateChain
	}
	return nil
}

func (x *LaunchAuthenticatedEndpointRequest) GetPemPrivateKey() []byte {
	if x != nil {
		return x.PemPrivateKey
	}
	return nil
}

// Errors to be passed via the gRPC built in error handling mechanism
type LaunchAuthenticatedEndpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *LaunchAuthenticatedEndpointResponse) Reset() {
	*x = LaunchAuthenticatedEndpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LaunchAuthenticatedEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchAuthenticatedEndpointResponse) ProtoMessage() {}

func (x *LaunchAuthenticatedEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vkvmagent_v0_bootstrap_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchAuthenticatedEndpointResponse.ProtoReflect.Descriptor instead.
func (*LaunchAuthenticatedEndpointResponse) Descriptor() ([]byte, []int) {
	return file_vkvmagent_v0_bootstrap_proto_rawDescGZIP(), []int{4}
}

var File_vkvmagent_v0_bootstrap_proto protoreflect.FileDescriptor

var file_vkvmagent_v0_bootstrap_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x76, 0x30, 0x2f, 0x62,
	0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x22, 0x19, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6f, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x13, 0x65, 0x63, 0x32, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x21, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e,
	0x45, 0x43, 0x32, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x52, 0x13, 0x65, 0x63, 0x32, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x99, 0x01, 0x0a, 0x13, 0x45, 0x43, 0x32,
	0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x2a, 0x0a, 0x10, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x44, 0x6f, 0x63, 0x75,
	0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x69, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x26, 0x0a, 0x0e,
	0x70, 0x6b, 0x63, 0x73, 0x37, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x70, 0x6b, 0x63, 0x73, 0x37, 0x53, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x12, 0x2e, 0x0a, 0x12, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x43,
	0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x12, 0x73, 0x69, 0x67, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x65, 0x22, 0x7c, 0x0a, 0x22, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x75,
	0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x70, 0x65,
	0x6d, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x13, 0x70, 0x65, 0x6d, 0x43, 0x65, 0x72, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12, 0x24, 0x0a, 0x0d,
	0x70, 0x65, 0x6d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0d, 0x70, 0x65, 0x6d, 0x50, 0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x22, 0x25, 0x0a, 0x23, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x75, 0x74, 0x68,
	0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xf8, 0x01, 0x0a, 0x0e, 0x41, 0x67,
	0x65, 0x6e, 0x74, 0x42, 0x6f, 0x6f, 0x74, 0x73, 0x74, 0x72, 0x61, 0x70, 0x12, 0x61, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x12, 0x25, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x82, 0x01, 0x0a, 0x1b, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e,
	0x74, 0x69, 0x63, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12,
	0x30, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30, 0x2e, 0x4c,
	0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x65, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x31, 0x2e, 0x76, 0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x76, 0x30,
	0x2e, 0x4c, 0x61, 0x75, 0x6e, 0x63, 0x68, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x77, 0x73, 0x2f, 0x61, 0x77, 0x73, 0x2d, 0x76, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x2d, 0x6b, 0x75, 0x62, 0x65, 0x6c, 0x65, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x6b, 0x76, 0x6d, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x5f, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_vkvmagent_v0_bootstrap_proto_rawDescOnce sync.Once
	file_vkvmagent_v0_bootstrap_proto_rawDescData = file_vkvmagent_v0_bootstrap_proto_rawDesc
)

func file_vkvmagent_v0_bootstrap_proto_rawDescGZIP() []byte {
	file_vkvmagent_v0_bootstrap_proto_rawDescOnce.Do(func() {
		file_vkvmagent_v0_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(file_vkvmagent_v0_bootstrap_proto_rawDescData)
	})
	return file_vkvmagent_v0_bootstrap_proto_rawDescData
}

var file_vkvmagent_v0_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_vkvmagent_v0_bootstrap_proto_goTypes = []interface{}{
	(*GetAgentIdentityRequest)(nil),             // 0: vkvmagent.v0.GetAgentIdentityRequest
	(*GetAgentIdentityResponse)(nil),            // 1: vkvmagent.v0.GetAgentIdentityResponse
	(*EC2InstanceIdentity)(nil),                 // 2: vkvmagent.v0.EC2InstanceIdentity
	(*LaunchAuthenticatedEndpointRequest)(nil),  // 3: vkvmagent.v0.LaunchAuthenticatedEndpointRequest
	(*LaunchAuthenticatedEndpointResponse)(nil), // 4: vkvmagent.v0.LaunchAuthenticatedEndpointResponse
}
var file_vkvmagent_v0_bootstrap_proto_depIdxs = []int32{
	2, // 0: vkvmagent.v0.GetAgentIdentityResponse.ec2InstanceIdentity:type_name -> vkvmagent.v0.EC2InstanceIdentity
	0, // 1: vkvmagent.v0.AgentBootstrap.GetAgentIdentity:input_type -> vkvmagent.v0.GetAgentIdentityRequest
	3, // 2: vkvmagent.v0.AgentBootstrap.LaunchAuthenticatedEndpoint:input_type -> vkvmagent.v0.LaunchAuthenticatedEndpointRequest
	1, // 3: vkvmagent.v0.AgentBootstrap.GetAgentIdentity:output_type -> vkvmagent.v0.GetAgentIdentityResponse
	4, // 4: vkvmagent.v0.AgentBootstrap.LaunchAuthenticatedEndpoint:output_type -> vkvmagent.v0.LaunchAuthenticatedEndpointResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vkvmagent_v0_bootstrap_proto_init() }
func file_vkvmagent_v0_bootstrap_proto_init() {
	if File_vkvmagent_v0_bootstrap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vkvmagent_v0_bootstrap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentIdentityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_bootstrap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAgentIdentityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_bootstrap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EC2InstanceIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_bootstrap_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LaunchAuthenticatedEndpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vkvmagent_v0_bootstrap_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LaunchAuthenticatedEndpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vkvmagent_v0_bootstrap_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vkvmagent_v0_bootstrap_proto_goTypes,
		DependencyIndexes: file_vkvmagent_v0_bootstrap_proto_depIdxs,
		MessageInfos:      file_vkvmagent_v0_bootstrap_proto_msgTypes,
	}.Build()
	File_vkvmagent_v0_bootstrap_proto = out.File
	file_vkvmagent_v0_bootstrap_proto_rawDesc = nil
	file_vkvmagent_v0_bootstrap_proto_goTypes = nil
	file_vkvmagent_v0_bootstrap_proto_depIdxs = nil
}
