@startuml
'https://plantuml.com/sequence-diagram

VirtualKubelet -> Ec2Provider: NewEc2Provider
Ec2Provider -> config: LoadInitParams
Ec2Provider -> EniNode: GetOrCreateEniNode
Ec2Provider -> ComputeManager: NewComputeManager
ComputeManager -> WarmPoolManager: CreatePools (if WarmPoolConfig exists and is valid)

@enduml