# This sample, non-production-ready code contains a Virtual Kubelet EC2-based provider and example VM Agent implementation.
# © 2021 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
#
# This AWS Content is provided subject to the terms of the AWS Customer Agreement
# available at http://aws.amazon.com/agreement or other written agreement between
# Customer and either Amazon Web Services, Inc. or Amazon Web Services EMEA SARL or both.

# Example pod to test Virtual Kubelet configuration
apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: virtual-kubelet
  annotations:
    # All values below pertain to the pod EC2 instance
    compute.amazonaws.com/tags: '{"Name": "Virtual Kubelet Pod Instance"}'
    compute.amazonaws.com/security-groups: sg-badf005ba117ab1e5
    compute.amazonaws.com/instance-profile: virtual-kubelet-instance-profile
    compute.amazonaws.com/image-id: ami-badf005ba117ab1e5
    compute.amazonaws.com/key-pair: "keypair"
    compute.amazonaws.com/subnet-id: subnet-badf005ba117ab1e5
    compute.amazonaws.com/instance-type: m6g.medium
spec:
  # NOTE This is an example container but nothing is actually launched unless implemented in the VKVMAgent
  containers:
    - name: echo
      image: ealen/echo-server
  # The `nodeSelector` and `tolerations` ensure this pod only runs on virtual-kubelet nodes
  nodeSelector:
    type: virtual-kubelet
  tolerations:
    - key: "virtual-kubelet.io/provider"
      operator: Exists
      effect: NoSchedule
